# Generated by Django 4.1.4 on 2022-12-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankings',
            name='age',
            field=models.IntegerField(max_length=15, null=True, verbose_name='AGE'),
        ),
        migrations.AlterField(
            model_name='rankings',
            name='byeweek',
            field=models.IntegerField(max_length=15, null=True, verbose_name='BYE WEEK'),
        ),
        migrations.AlterField(
            model_name='rankings',
            name='playername',
            field=models.CharField(max_length=50, null=True, verbose_name='PLAYER NAME'),
        ),
        migrations.AlterField(
            model_name='rankings',
            name='pos',
            field=models.CharField(max_length=50, null=True, verbose_name='POS'),
        ),
        migrations.AlterField(
            model_name='rankings',
            name='rank',
            field=models.IntegerField(max_length=15, null=True, verbose_name='RK'),
        ),
        migrations.AlterField(
            model_name='rankings',
            name='team',
            field=models.CharField(max_length=50, null=True, verbose_name='TEAM'),
        ),
        migrations.AlterField(
            model_name='rankings',
            name='tiers',
            field=models.IntegerField(max_length=15, null=True, verbose_name='TIERS'),
        ),
    ]
