# Generated by Django 4.1.4 on 2022-12-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0002_alter_rankings_age_alter_rankings_byeweek_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankings',
            name='rank',
        ),
    ]
