# Generated by Django 4.1.4 on 2022-12-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0004_rankings_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankings',
            old_name='rank',
            new_name='RK',
        ),
        migrations.RenameField(
            model_name='rankings',
            old_name='tiers',
            new_name='TIERS',
        ),
    ]
