# Generated by Django 4.0.1 on 2022-12-15 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0008_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_players', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomid_list', to='Drafter.room')),
                ('roster', models.ManyToManyField(related_name='player_roster', to='Drafter.Roster')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='team',
            field=models.ManyToManyField(related_name='teams_list', to='Drafter.Teams'),
        ),
    ]
