# Generated by Django 4.0.1 on 2022-12-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0010_alter_teams_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rankings',
            field=models.ManyToManyField(related_name='rankings_list', to='Drafter.Rankings'),
        ),
    ]
