# Generated by Django 4.0.1 on 2022-12-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0011_room_rankings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankings',
            name='byeweek',
            field=models.CharField(max_length=15, null=True, verbose_name='BYE WEEK'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rankings',
            field=models.ManyToManyField(related_name='teams_list', to='Drafter.Rankings'),
        ),
    ]
