# Generated by Django 4.0.1 on 2022-12-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0012_alter_rankings_byeweek_alter_room_rankings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankings',
            name='age',
            field=models.CharField(max_length=15, null=True, verbose_name='AGE'),
        ),
    ]
