# Generated by Django 4.0.1 on 2022-12-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0014_drafted_remove_room_rankings_room_drafted'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
