# Generated by Django 4.0.1 on 2022-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0015_room_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankings',
            old_name='rank',
            new_name='runk',
        ),
        migrations.AddField(
            model_name='rankings',
            name='posrank',
            field=models.CharField(max_length=50, null=True, verbose_name='POSRANK'),
        ),
        migrations.AddField(
            model_name='teams',
            name='req_position',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
