# Generated by Django 4.0.1 on 2022-12-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0016_rename_rank_rankings_runk_rankings_posrank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankings',
            old_name='runk',
            new_name='rank',
        ),
    ]
