# Generated by Django 4.0.1 on 2022-12-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0017_rename_runk_rankings_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rounds',
            field=models.IntegerField(default=15),
        ),
    ]
