# Generated by Django 4.0.1 on 2023-01-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0018_room_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_turn',
            field=models.CharField(default='AI', max_length=50),
        ),
    ]
