# Generated by Django 4.0.1 on 2023-01-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0020_room_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rounds_remaining',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
