# Generated by Django 4.0.1 on 2023-01-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0021_room_rounds_remaining_alter_room_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='pos',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
