# Generated by Django 4.0.1 on 2023-01-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0022_roster_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='drafts',
            field=models.ManyToManyField(related_name='drafts', to='Drafter.Drafts'),
        ),
    ]
