# Generated by Django 4.0.1 on 2023-01-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drafter', '0023_drafts_user_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
